### ISSUE TITLE
Properly handling "Umlauts" / special characters

### ISSUE THREAD

**Issue by JayVii** [davorg/perlanet#7] opened 2018-06-20 10:41 UTC
perlanet doesn't seem to properly handle special characters like "umlauts" in the german language in URLs.

tested on: perlanet, version 1.1.2

* * *

Example:
[This URL](https://posteo.de/blog/wir-suchen-verstärkung--10) becomes
this: https://posteo.de/blog/wir-suchen-verst%25C3%25A4rkung--10 when it should be
this: https://posteo.de/blog/wir-suchen-verst%C3%A4rkung--10

As you can see, the first "%" in "%C3%A4" is actually encoded to "%25" which leads to the URL being broken.

I this issue isn't grave, but a fairly frequent annoyance for me, as german news-outlets and blogs apparently love to use Umlauts in their URLs for some reason.

**Comment by davorg** [comment] 2018-06-20 10:45
I can look at this problem, of course, but it would be easier if you had a failing test.

Do you see the problem when you're accessing the `link` attribute on an Entry object?

**Comment by JayVii** [comment] 2018-06-20 11:08
> Do you see the problem when you're accessing the `link` attribute on an Entry object?

I am not entirely clear, on what information you need, I am sorry.

perlanet itself doesn't give me any error, when running it:

```
** GET https://posteo.de/blog/feed?format=atom ==> 200 OK
```

Looking at the generated HTML obviously gives me the broken url as well:

```
<a href="https://posteo.de/blog/wir-suchen-verst%25C3%25A4rkung--10">
```

*Hovering* the entry shows me the correct URL, however:
```
https://posteo.de/blog/wir-suchen-verst%C3%25A4rkung--1
```

Again, sorry if this is not, what you asked for

**Comment by davorg** [comment] 2018-06-20 11:13
Ok. It seems that the problem is not with Perlanet but, rather, with the example template that I assume you've copied for your system. The bit that outputs the link looks like this:

    [% entry.link | url | html %]

Note that it's passing the link through two Template Toolkit filters, `url` and `html`. The `url` filter's job is to replace unsafe characters with their URL-safe version. And one character it replaces is `%` (which it replaces with `%25`). But in this case, your URL is already correctly encoded, so you end up with a "double-encoded" character.

The simple solution for you is simply to remove the `url` filter from your template, so it looks like this:

    [% entry.link | html %]

And I need to think about whether it's a good idea to remove it completely from the example template.

Thanks for pointing it out.

**Comment by davorg** [comment] 2018-06-20 12:14
Actually, I think that the module which is doing the work here (XML::Feed) is cleverer than I am. I've just run a test with a completely unescaped input URL (https://posteo.de/blog/wir-suchen-verstärkung--10) and the output ended up properly encoded (https://posteo.de/blog/wir-suchen-verst%C3%A4rkung--10).

So I'm pretty sure that just removing the filter will do the right thing. I'll get a new release out as soon as I can.

I'll close this ticket.

**Closed by davorg** 2018-06-20 12:14 UTC
Labels: bug
